# Generated by Django 6.0.3 on 2026-03-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvtemplate',
            name='docx_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
