# Generated by Django 6.0.3 on 2026-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_hide_legacy_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvtemplate',
            name='description',
            field=models.TextField(help_text='Description courte (1-2 lignes)'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='long_description',
            field=models.TextField(blank=True, help_text='Description détaillée et avantages'),
        ),
    ]
