# Generated by Django 6.0.3 on 2026-03-16 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mon CV', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('generated', 'Généré')], default='draft', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='cvs/generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cvs', to='templates.cvtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
