# Generated by Django 6.0.3 on 2026-06-10 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='ai_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cv',
            name='ai_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='ai_messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='ai_status',
            field=models.CharField(choices=[('idle', 'En attente'), ('processing', 'Traitement IA'), ('ready', 'IA prête'), ('failed', 'Erreur IA')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cvs/generated/'),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_offer_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/offers/'),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_offer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_offer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/source/'),
        ),
        migrations.AddField(
            model_name='cv',
            name='template_mode',
            field=models.CharField(choices=[('selected', 'Utiliser le modèle choisi'), ('match_upload', "Se rapprocher de l'ancien CV")], default='selected', max_length=30),
        ),
        migrations.AlterField(
            model_name='cv',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('ai_ready', 'Optimisé par IA'), ('generated', 'Généré'), ('failed', 'Erreur')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('single_cv', 'CV individuel'), ('weekly', 'Abonnement semaine'), ('extra_ai', 'Question IA supplémentaire')], max_length=30)),
                ('amount_xof', models.PositiveIntegerField()),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('authorization_url', models.URLField(blank=True)),
                ('access_code', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('abandoned', 'Abandonné')], default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cvs.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Paystack',
                'verbose_name_plural': 'Transactions Paystack',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('single_cv', 'CV individuel'), ('weekly', 'Abonnement semaine'), ('extra_ai', 'Question IA supplémentaire')], max_length=30)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ai_credits', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='cvs.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_access_grants', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grant', to='cvs.paymenttransaction')),
            ],
            options={
                'verbose_name': "Droit d'accès CV",
                'verbose_name_plural': "Droits d'accès CV",
                'ordering': ['-created_at'],
            },
        ),
    ]
