# Generated by Django 6.0.3 on 2026-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_cv_ai_data_cv_ai_error_cv_ai_messages_cv_ai_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='plan_type',
            field=models.CharField(choices=[('single_cv', 'CV individuel'), ('weekly', 'Abonnement semaine'), ('extra_ai', 'Prolongation IA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan_type',
            field=models.CharField(choices=[('single_cv', 'CV individuel'), ('weekly', 'Abonnement semaine'), ('extra_ai', 'Prolongation IA')], max_length=30),
        ),
    ]
