# Generated by Django 6.0.3 on 2026-06-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0004_cv_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='cv_credits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='plan_type',
            field=models.CharField(choices=[('trial', 'Essai gratuit'), ('weekly', 'Abonnement semaine'), ('single_cv', 'CV individuel'), ('extra_ai', 'Prolongation IA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan_type',
            field=models.CharField(choices=[('trial', 'Essai gratuit'), ('weekly', 'Abonnement semaine'), ('single_cv', 'CV individuel'), ('extra_ai', 'Prolongation IA')], max_length=30),
        ),
    ]
